### ISSUE TITLE
feature to allow to set which exchange per pair

### ISSUE THREAD

**Issue by azorpax** [alipirpiran/Crypto-Price-Tracker-for-Gnome-Shell#17]
There are some pairs that are not available in some currently supported exchanges (Binance and OKX). 
eg. 
BNB/USDT is available in Binance but not in OKX
CRO/USDT is available in OKX but not in Binance
etc...

Currently, we get the price from the supported exchange which is Binance and OKX, and we can only select one exchange to be used for all the pairs.

This request will allow the user to set an exchange per pair. 
With this request, I'm thinking we could add an option during adding a pair to select a specific exchange or use the active exchange. 

Any thoughts?

**Comment by alipirpiran** [comment]
Yes its good idea.
In the add coin section, we can add options to select specific exchange, and an option for default or active ... exchange.
Or we can remove the section that is for selecting exchange, and the user just select exchange when adding new pair.

**Comment by azorpax** [comment]
I like the idea of removing the section for selecting an exchange. with that, we don't need an additional handler for those pairs that have no specific exchange defined. 
In relation to that, I have a question about how we are going to handle the old data of the users that have no defined exchange if we implement this. Do you have any idea or reference on how we can fix those data?

**Comment by alipirpiran** [comment]
I think we can check current active exchange for those users. And in the init function or the function that is setting the coins array,whene we get coins from setting, check for each coin, if exchange property is null, set current active exchange for them and save it.
Because we just delete exchange section from ui, and active exchange is stil saved because it is in the schema file.
And next time, all the coins have their specific exchange and the active exchange in the schema file become useless.

**Comment by azorpax** [comment]
alright, I got the idea. 
you can assign this to me if you want.

**Comment by alipirpiran** [comment]
Ok, thanks. For the schema file we neet to compile it again after edit it. Do you know the command?

**Comment by azorpax** [comment]
Yes, with this guide. https://gjs.guide/extensions/development/preferences.html#compiling-the-schema

I'm going to add a new property named "exchange" with a default value of "Binance"
